sudo: required
dist: xenial

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

install:
  # Install conan
  - sudo apt-get install -qq python-pip
  - sudo -H pip2 install conan
  - conan profile new --detect default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan remote add ess-dmsc https://api.bintray.com/conan/ess-dmsc/conan

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./bin/udmstest
  - ./bin/utest
