language: cpp
compiler: gcc

sudo: required

dist: bionic
addons:
  apt:
    packages:
#      - cloc
#      - doxygen
#      - lcov
#      - libtool
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install --user cpp-coveralls

install:
  - sudo -H pip3 install conan
  - sudo -H pip3 install gcovr==3.4
  - conan profile new --detect default
  - conan profile update settings.compiler.libcxx=libstdc++11 default

before_script:
  - mkdir build
  - cd build
  - cmake -DCOV=1 ..
#  - cmake ..

script:
  - make
  - ./bin/ms_demo > null
  - ./bin/full_demo > null
  - make coverage

after_success:
  - ce ..
  - coveralls --build-root build --gcov-options '\-lp' \
    -e build/lib \
    -e build/bin/ms_demo \
    -e build/bin/full_demo
