language: cpp
compiler: gcc

sudo: required

dist: bionic
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install --user cpp-coveralls

install:
  - sudo -H pip3 install conan
  - sudo -H pip3 install gcovr==3.4
  - sudo -H pip3 install codecov
  - conan profile new --detect default
  - conan profile update settings.compiler.libcxx=libstdc++11 default

before_script:
  - mkdir build
  - cd build
  - cmake -DCOV=1 ..

script:
  - make
  - ./bin/ms_demo > null
  - ./bin/full_demo > null
  - make coverage

after_success:
  - cd ..
  - coveralls --build-root build --gcov-options '\-lp' -E ".*gtest.*" -E ".*CMakeFiles.*" -e build/lib -e build/tests -e build/examples
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
