language: cpp
compiler: gcc

sudo: required

dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
#      - cloc
#      - doxygen
#      - lcov
#      - libtool
      - python3-pip

install:
  # Install conan
  - sudo -H pip3 install conan
  - sudo -H pip3 install gcovr==3.4
  - conan profile new --detect default
  - conan profile update settings.compiler.libcxx=libstdc++11 default

before_script:
  - mkdir build
  - cd build
  - cmake -DCOV=1 ..
#  - cmake ..

script:
  - make
  - ./bin/ms_demo > null
  - ./bin/full_demo > null
#  - make coverage


