language: cpp
compiler: gcc

sudo: required

dist: bionic
addons:
  apt:
    packages:
#      - cloc
#      - doxygen
#      - lcov
#      - libtool
      - python-pip
      - python-setuptools

before_install:
  - pip install --user cpp-coveralls

install:
  - sudo -H pip install conan
  - sudo -H pip install gcovr==3.4
  - conan profile new --detect default
  - conan profile update settings.compiler.libcxx=libstdc++11 default

before_script:
  - mkdir build
  - cd build
  - cmake -DCOV=1 ..
#  - cmake ..

script:
  - make
  - ./bin/ms_demo > null
  - ./bin/full_demo > null
  - make coverage

after_success:
  - cd ..
  - coveralls --root . --build-root build --gcov-options '\-lp' -E ".*gtest.*" -E ".*CMakeFiles.*" -e build/lib
