version: 2.1

jobs:
  build-run:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            export FORCED_ROOT=1
            ./uncertain.sh install
      - run:
          name: CMake
          command: |
            mkdir build
            cd build
            cmake -DCOV=1 ..
      - run:
          name: Build
          command: |
            cd build
            make everything
      - run:
          name: Run tests and demos
          command: |
            ./uncertain.sh test
      - run:
          name: Upload coverage reports
          command: |
            ./uncertain.sh cov --upload

workflows:
  commit:
    jobs:
      - build-run
