version: 2.1

jobs:
  run-tests:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            export FORCED_ROOT=1
            sudo -E -H ./uncertain.sh install
            ./uncertain.sh configure
      - run:
          name: Run tests and demos
          command: |
            ./uncertain.sh test
      - run:
          name: Upload coverage reports
          command: |
            export TRAVIS_JOB_ID="#${CIRCLE_BUILD_NUM}"
            ./uncertain.sh cov --upload

  static-checks:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            export FORCED_ROOT=1
            sudo -E -H ./uncertain.sh install
            ./uncertain.sh configure
      - run:
          name: Build
          command: |
            ./uncertain.sh build
      - run:
          name: Perform static checks
          command: |
            ./uncertain.sh check

  pre-commit-checks:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: Install pre-commit
          command: |
            pip install pre-commit
      - run:
          name: Run pre-commit hooks
          command: |
            merge_base=$(git merge-base -a HEAD origin/master)
            changed_files=$(git diff --name-only $merge_base...HEAD)
            echo "Changed files since branched from origin/master: " $changed_files
            git reset --soft $merge_base
            pre-commit run --show-diff-on-failure --files $changed_files

workflows:
  circleci-tests:
    jobs:
      - run-tests
      - static-checks
      - pre-commit-checks
