version: 2.1

jobs:
  build-run:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            export FORCED_ROOT=1
            ./uncertain.sh install
      - run:
          name: CMake
          command: |
            mkdir build
            cd build
            cmake -DCOV=1 ..
      - run:
          name: Build
          command: |
            cd build
            make everything
      - run:
          name: Run tests and demos
          command: |
            ./uncertain.sh test
      - run:
          name: Upload coverage reports
          command: |
            TRAVIS_JOB_ID="#${CIRCLE_BUILD_NUM}"
            ./uncertain.sh cov --upload
      - run:
          name: Upload coveralls
          command: |
            echo -e "service_name: circle-ci\n" > .coveralls.yml
            TRAVIS_JOB_ID="#${CIRCLE_BUILD_NUM}"
            coveralls -r . -t $COVERALLS_REPO_TOKEN --build-root build --gcov-options '\-lp' -E ".*gtest.*" -E ".*CMakeFiles.*" -e build/lib -e build/tests -e build/examples -e tests -e examples

workflows:
  commit:
    jobs:
      - build-run
